sudo: required

language: c

env:
  global:
    # for the latest public release
    # - GAPCONTAINER="gapsystem/gap-docker"
    # - GAPDIRNAME="gap4r8"
    # for the tests of the stable-4.8 branch
    # - GAPCONTAINER="gapsystem/gap-docker-stable"
    # - GAPDIRNAME="gap-stable-4.8"
    # for the tests of the master branch
    - GAPCONTAINER="gapsystem/gap-docker-master"
    - GAPDIRNAME="gap-master"

  matrix:
    - PKG_NAME=ace
    - PKG_NAME=aclib
    - PKG_NAME=alnuth
    - PKG_NAME=anupq
#    - PKG_NAME=atlasrep # default 6 DIFFS | no pkg 8 DIFFS | all pkg 6 DIFFS
    - PKG_NAME=autodoc
    - PKG_NAME=automata
#    - PKG_NAME=automgrp # default 1 DIFFS | no pkg 1 DIFFS | all pkg 1 DIFFS
    - PKG_NAME=autpgrp
    - PKG_NAME=carat
    - PKG_NAME=circle
    - PKG_NAME=cohomolo
    - PKG_NAME=congruence
    - PKG_NAME=crime
    - PKG_NAME=crisp
    - PKG_NAME=crypting
    - PKG_NAME=cryst
    - PKG_NAME=crystcat
#    - PKG_NAME=ctbllib # default 14 DIFFS | no pkg 14 DIFFS | all pkg 14 DIFFS
    - PKG_NAME=cubefree
    - PKG_NAME=curlinterface
    - PKG_NAME=cvec
#    - PKG_NAME=datastructures # default PASS | no pkg PASS | all pkg 1 DIFFS
    - PKG_NAME=deepthought
    - PKG_NAME=design
    - PKG_NAME=digraphs
    - PKG_NAME=example
    - PKG_NAME=factint
#    - PKG_NAME=ferret # default PASS | no pkg PASS | all pkg 2 DIFFS
    - PKG_NAME=fga
    - PKG_NAME=fining
    - PKG_NAME=float
    - PKG_NAME=format
    - PKG_NAME=forms
    - PKG_NAME=fplsa
    - PKG_NAME=fr
    - PKG_NAME=francy
#    - PKG_NAME=gbnp # default 1 DIFFS | no pkg 1 DIFFS | all pkg 1 DIFFS
    - PKG_NAME=genss
    - PKG_NAME=grape
    - PKG_NAME=groupoids
    - PKG_NAME=grpconst
    - PKG_NAME=guarana
    - PKG_NAME=guava
    - PKG_NAME=hap
#    - PKG_NAME=hapcryst # default 9 DIFFS | no pkg 9 DIFFS | all pkg 9 DIFFS
    - PKG_NAME=hecke
#    - PKG_NAME=help # default 1 DIFFS | no pkg 1 DIFFS | all pkg 1 DIFFS
    - PKG_NAME=idrel
    - PKG_NAME=images
    - PKG_NAME=intpic
    - PKG_NAME=io
    - PKG_NAME=irredsol
    - PKG_NAME=json
    - PKG_NAME=jupyterkernel
#    - PKG_NAME=jupyterviz # default 22 DIFFS | no pkg 22 DIFFS | all pkg 22 DIFFS
    - PKG_NAME=kan
    - PKG_NAME=kbmag
    - PKG_NAME=laguna
    - PKG_NAME=liealgdb
    - PKG_NAME=liepring
    - PKG_NAME=loops
    - PKG_NAME=lpres
    - PKG_NAME=majoranaalgebras
    - PKG_NAME=mapclass
    - PKG_NAME=matgrp
    - PKG_NAME=modisom
    - PKG_NAME=normalizinterface
    - PKG_NAME=nq
    - PKG_NAME=numericalsgps
    - PKG_NAME=openmath
    - PKG_NAME=orb
#    - PKG_NAME=packagemanager
    - PKG_NAME=patternclass
    - PKG_NAME=permut
    - PKG_NAME=polenta
#    - PKG_NAME=polycyclic # default PASS | no pkg PASS | all pkg 2 DIFFS
#    - PKG_NAME=polymaking # default 5 DIFFS | no pkg 5 DIFFS | all pkg 5 DIFFS
    - PKG_NAME=primgrp
#    - PKG_NAME=profiling # default 1 DIFFS | no pkg 1 DIFFS | all pkg 1 DIFFS
    - PKG_NAME=qpa
    - PKG_NAME=radiroot
#    - PKG_NAME=rcwa # default 12 DIFFS | no pkg 12 DIFFS | all pkg 13 DIFFS
    - PKG_NAME=rds
#    - PKG_NAME=recog # default PASS | no pkg PASS | all pkg 1 DIFFS
    - PKG_NAME=repsn
    - PKG_NAME=resclasses
    - PKG_NAME=scscp
    - PKG_NAME=semigroups # default CRASH | no pkg CRASH | all pkg CRASH
    - PKG_NAME=sglppow
    - PKG_NAME=sgpviz
    - PKG_NAME=simpcomp
    - PKG_NAME=singular
    - PKG_NAME=smallgrp
    - PKG_NAME=smallsemi
#    - PKG_NAME=sonata # default PASS | no pkg PASS | all pkg 2 DIFFS
    - PKG_NAME=sophus
    - PKG_NAME=spinsym
    - PKG_NAME=thelma
    - PKG_NAME=tomlib
    - PKG_NAME=toric
    - PKG_NAME=transgrp
    - PKG_NAME=unipot
    - PKG_NAME=unitlib
    - PKG_NAME=utils
    - PKG_NAME=uuid
    - PKG_NAME=walrus
    - PKG_NAME=wedderga
#    - PKG_NAME=xmod # default PASS | no pkg PASS | all pkg 1 DIFFS
    - PKG_NAME=xmodalg
    - PKG_NAME=yangbaxter
    - PKG_NAME=zeromqinterface

services:
  - docker

before_install:
- docker pull ${GAPCONTAINER}

script:
    - docker version
    - docker run -v $PWD:/home/gap/travis/ ${GAPCONTAINER} /bin/sh -c "GAPDIRNAME=${GAPDIRNAME} PKG_NAME=${PKG_NAME} TERM=xterm LANG=en_GB.UTF-8 /home/gap/travis/ci.sh"

notifications:
  slack:
    secure: v4dgA2Q7oz3R3YZ3AJXt8ZGKjH8ZZriUmRNhmm4XxOc2pFAoUBtozyJQFKmIVFPXYmZYcr84WL/fpnHUx7Me53xE96fbQ/QPSFT8y4GxQTTL7IwukgkMjLjZUBzT70Q1lmKayPn50dAHVmYjK2F5F08U3u5lytfB6OLfqI80O135wNwSJ8zZMXKeLoyWsGmJftVM/kaC39E8puCuArnYVW7rnkj55NHBFcA9i65TEjw0jxPrEA91lMboozFX3bCGjgc7y+tMJOxiXL3agI3yiWN7G/0P4DMgkMxrXWUaLuDjM2MbuzCvJMp5ef1cvyCnGOKlv1IEx2+pylcxe5mWAiCfweFz2s+DSqCJOpTUoAopu44nN2ZwKpyBrm2cU3ycnI1JFeklwUrFPahz9qQJIc3rotTpXYk+gMJOqUruS5BR4kRO8+7rmwx87V6rS2hwvHpdPKw+myVwa/XMdxgG6k2TubxBqJHHta7U3U3N38jdVhDMYoAN2bum0YxloZ61zqMEpZxbRZuepjZWBsdSzepLAfwVg80SzIhyYPHqYVO3szw0I0/4ebV8kj44CijSBKKTc85yGMNLGrajV+9YVtA37T3cTZp9dWbd+t5VCrF03KXY4RGonG8vfRhmthaBJWP245cMhY0SoqQP40KzCpzEIwmjR77yWs+Iw41Bqyo=
